= GeoPose 1.0 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies the conformance of the implementation under test (IUT) with respect to the OGC GeoPose 1.0 Data Exchange Draft Standard. Conformance testing is a kind of "black box" testing that examines the externally visible characteristics or behaviors of the IUT while disregarding any implementation details.

Several conformance classes are defined in the principal specification; the ones
listed below are covered by this test suite:

* /conf/basic-ypr-encoding-json/definition, Conformance test A.37
* /conf/basic-quaternion-encoding-json/definition, Conformance test A.38
* /conf/advanced-encoding-json/definition, Conformance test A.40

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a 
conforming implementation.

1. https://docs.ogc.org/dis/21-056r10/21-056r10.html[OGC GeoPose 1.0 Data Exchange Draft Standard (OGC 21-056r10)]


== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.geopose10`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Basic YPR
|org.opengis.cite.geopose10.encodings.json.BasicYPR

|Basic Quaternion
|org.opengis.cite.geopose10.encodings.json.BasicQuaternion

|Advanced
|org.opengis.cite.geopose10.encodings.json.Advanced

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These ate summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|basicypr
|file
|O
|A file to upload

|basicquaternion
|file
|O
|A file to upload

|advanced
|file
|O
|A file to upload


|===
